server:
  port: ${port.book-api}

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:data/schema.sql
    data: classpath:data/data.sql
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  thymeleaf:
    cache: false
  banner:
    location: classpath:banner/banner.txt

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

---
spring:
  profiles: local

---
spring:
  profiles: dev